[[chains]]
id = 'core-1'
clear_interval = 10
client_refresh_rate = '1/30'
[chains.packet_filter]
policy = 'allow'
list = [

    [ 'transfer', 'channel-24' ], # cosmoshub-4 transfer

    ['icacontroller-lscosmos_pstake_delegation_account','channel-133'], # cosmoshub-4 icacontroller

    ['icacontroller-lscosmos_pstake_reward_account, osmosis-1','channel-53'], # cosmoshub-4 icacontroller

    ['icacontroller-persistence18dsfsljczehwd5yem9qq2jcz56dz3shp48j3zj','channel-141'], # cosmoshub-4 icacontroller

    ['transfer','channel-6'], # osmosis-1 transfer

    ['icacontroller-osmosis-1.delegate','channel-142'], # osmosis-1 icacontroller

    ['icacontroller-osmosis-1.rewards','channel-144'], # osmosis-1 icacontroller

    [ 'transfer', 'channel-131' ], # dydx-mainnet-1 transfer

    [ 'transfer', 'channel-136' ], # neutron-1 transfer

    [ 'transfer', 'channel-132' ], # noble-1 transfer

    [ 'transfer', 'channel-129' ], # kava_2222-10 transfer

    ['icacontroller-*','*'], # icacontroller wildcard

]

[[chains]]
id = 'osmosis-1'
client_refresh_rate = '1/30'
[chains.packet_filter]
policy = 'allow'
list = [ 

    [ 'transfer', 'channel-4' ], # core-1 transfer

    [ 'icahost', 'channel-14971' ], # core-1 icahost

    [ 'icahost', 'channel-15078' ], # core-1 icahost

    ['icahost','*'], # icahost wildcard

]

[[chains]]
id = 'cosmoshub-4'
client_refresh_rate = '1/30'
[chains.packet_filter]
policy = 'allow'
list = [ 

    [ 'transfer', 'channel-190' ], # core-1 transfer

    [ 'icahost', 'channel-733' ], # core-1 icahost

    [ 'icahost', 'channel-428' ], # core-1 icahost

    [ 'icahost', 'channel-763' ], # core-1 icahost

    ['icahost','*'], # icahost wildcard

]

[[chains]]
id = 'dydx-mainnet-1'
clear_interval = 25
client_refresh_rate = '1/30'
[chains.packet_filter]
policy = 'allow'
list = [

    [ 'transfer', 'channel-4' ], # core-1 transfer

    ['icahost','*'], # icahost wildcard

]

[[chains]]
id = 'neutron-1'
clear_interval = 25
client_refresh_rate = '1/30'
[chains.packet_filter]
policy = 'allow'
list = [ 

    [ 'transfer', 'channel-49' ], # core-1 transfer

]

[[chains]]
id = 'noble-1'
memo_prefix = 'relayed by CryptoCrew Validators'
client_refresh_rate = '1/30'
[chains.packet_filter]
policy = 'allow'
list = [

    [ 'transfer', 'channel-43' ], # core-1 transfer

]

[[chains]]
id = 'kava_2222-10'
memo_prefix = 'relayed by CryptoCrew Validators'
client_refresh_rate = '1/30'
[chains.packet_filter]
policy = 'allow'
list = [ 
  
    [ 'transfer', 'channel-134' ], # core-1 transfer

]


[[chains]]
id = "kaiyo-1"
clear_interval = 25
client_refresh_rate = '1/30'
[chains.packet_filter]
policy = "allow"
list = [ 

#    [ "transfer", "channel-75" ], # neutron-1

]


[global]
log_level = 'debug'

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 25
clear_on_start = true
tx_confirmation = true